#!/bin/bash


#ambil data
video_title="$(youtube-dl --get-title  $1)"
#video_name="$(youtube-dl --get-filename $1)"



#download
youtube-dl -f bestvideo+bestaudio $1



echo "pause 10 detik"

sleep 10

echo "proses upload selesai"
