#!/bin/bash

rm -rf filename.*

#ambil data
video_title="$(youtube-dl --get-title  $1)"
#video_name="$(youtube-dl --get-filename $1)"



#download
#youtube-dl --extract-audio --audio-format mp3 --audio-quality 9 -o "audio.mp3" $1
#youtube-dl -f "webm/mp4"  -o "filename.mp4" $1
youtube-dl -f "webm/mp4" -o "filename.mp4" $1



ffmpeg -y -i filename.* -filter_complex "[0]scale=in_w-8:in_h-8[v1];[0][v1]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2, pad=iw+4:ih+4:2:2:color=white, scale=760:-1[v2]; movie=bg.mp4:loop=999,setpts=N/(FRAME_RATE*TB), scale=1280:-1[v3] ;[v3][v2]overlay=shortest=1:x=2:y=(main_h/4.9);[0:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=stereo,asetrate=9/10*44100,atempo=10/9,lowpass=f=2500,highpass=f=400,volume=3,bass=g=-30,equalizer=f=10.5:width_type=o:width=1:g=-30, equalizer=f=31.5:width_type=o:width=1:g=-30,equalizer=f=63:width_type=o:width=1:g=-10, equalizer=f=125:width_type=o:width=1:g=-20,equalizer=f=250:width_type=o:width=1:g=-1.5,equalizer=f=500:width_type=o:width=1:g=-20,equalizer=f=1000:width_type=o:width=1:g=-20,equalizer=f=8000:width_type=o:width=3:g=1,equalizer=f=16000:width_type=o:width=3:g=1" -vcodec libx264 -pix_fmt yuv420p -r 30 -g 60 -b:v 800k -shortest -acodec libmp3lame -b:a 128k -ar 44100 -preset veryfast "output3.mp4"



#upload video	
youtube-upload --title="$video_title" --description="Copyright disclaimer! I do NOT own this $video_title video/song or the image featured in the video. All rights belong to it's rightful owner/owner's.No copyright infringement intended," --category=Entertainment --tags="$video_title" --recording-date="2011-03-10T15:32:17.0Z" --default-language="en" --default-audio-language="en" --privacy="private" --playlist "ICIKICIK" output3.mp4



sleep 2
