#!/bin/bash

rm -rf *.jpg
rm -rf *.mp3
rm -rf *.mp4
rm -rf *.mkv
rm -rf *.wav
rm -rf *.webm
rm -rf *.mov
rm -rf *.m4a
rm -rf filename.*
rm -rf audio.*


#ambil data
video_title="$(youtube-dl --get-title  $1)"
#video_name="$(youtube-dl --get-filename $1)"



#download
youtube-dl --write-thumbnail --extract-audio --audio-format mp3 --audio-quality 9 -o "audio.mp3" $1
#youtube-dl -f "webm/mp4"  -o "filename.mp4" $1
#youtube-dl  -o "filename.mp4" $1


#joined audio + video
#ffmpeg -i nosound.mkv -i audio.mp3 -c:v copy -c:a aac -strict experimental output.mkv


#joined audio + gambar
ffmpeg -loop 1 -i audio.jpg -i audio.mp3 -c:v libx264 -tune stillimage -c:a aac -strict experimental -b:a 192k -pix_fmt yuv420p -shortest output.mkv


#audio effects


#add metadata
ffmpeg -i output.mkv \
	-map_metadata -1 \
	-metadata title="GNG Project" \
	-metadata author="GNG Project" \
	-metadata composer="GNG Project" \
	-metadata language="eng" \
	-metadata copyright="Copyright 2016 GNG Project" \
	-metadata:s:a:0 title="GNG Project" \
	-metadata:s:a:0 author="GNG Project" \
	-metadata:s:a:0 composer="GNG Project" \
	-metadata:s:a:0 language="eng" \
	-metadata:s:a:0 copyright="Copyright 2016 GNG Project" \
	-metadata artist="GNG Project" \
	-metadata album_artist="GNG Project" \
	-metadata album="GNG Project" \
	-metadata date="GNG Project" \
	-metadata track="GNG Project" \
	-metadata genre="GNG Project" \
	-metadata publisher="GNG Project" \
	-metadata encoded_by="GNG Project" \
	-metadata performer="GNG Project" \
	-metadata TIT1="GNG Project" \
	-metadata TIT3="GNG Project" \
	-metadata disc="GNG Project" \
	-metadata TKEY="GNG Project" \
	-metadata TBPM="GNG Project" \
	-metadata encoder="GNG Project" \
	-c:v copy -c:a libmp3lame -q:a 9 -y out.mkv
	


#fast slowdown video
ffmpeg -i out.mkv -filter_complex "setpts=PTS/1.20;atempo=1.25" output2.mkv


	
#upload video	
youtube-upload --title="$video_title" --description="Copyright disclaimer! I do NOT own this $video_title video/song or the image featured in the video. All rights belong to it's rightful owner/owner's.No copyright infringement intended," --category=Music --tags="$video_title" --recording-date="2011-03-10T15:32:17.0Z" --default-language="en" --default-audio-language="en" --privacy="private" --playlist "None" output2.mkv




echo "pause 10 detik"

sleep 10

echo "proses upload selesai"
