#!/bin/bash

rm -rf *.jpg
rm -rf *.mp3
rm -rf *.mp4
rm -rf *.mkv
rm -rf *.wav
rm -rf *.webm
rm -rf *.mov
rm -rf *.m4a
rm -rf filename.*
rm -rf audio.*


#ambil data
video_title="$(youtube-dl --get-title  $1)"
video_name="$(youtube-dl --get-filename $1)"



#download
youtube-dl -f "webm/mp4"  -o "filename.mp4" $1
#youtube-dl  -o "filename.mp4" $1
avconv -i filename.* -vn -ab 192k -acodec libmp3lame -ac 2 audio.mp3


#cropblackbars
cropdetect="$(avconv -ss 13 -i filename.* -t 1 -vf "cropdetect=24:16:0" -preset ultrafast -f null - 2>&1 | awk '/crop/ { print $NF }' | tail -1)"
avconv -i filename.* -acodec copy -vf $cropdetect  scale.mp4


#speed audio video
sox --show-progress audio.mp3 output.mp3 tempo 1.60 pitch 500
avconv -i scale.mp4 -filter:v "setpts=1*PTS" -preset ultrafast speed.mp4



#joined audio + video
avconv -i speed.mp4 -i output.mp3 -c:v copy -c:a copy output.mp4


#remove metadata
avconv -i output.mp4 -map_metadata -1 -c:v copy -c:a copy out.mp4



#add metadata
avconv -i out.mp4 \
	-map_metadata -1 \
	-metadata title="Btt Project" \
	-metadata author="Btt Project" \
	-metadata composer="Btt Project" \
	-metadata copyright="Copyright © 2016 Btt Project" \
	-c:v copy -c:a libmp3lame -q:a 9 -y addmetadata.mp4
	
	

#scale and crop	
#avconv -i addmetadata.mkv -vf "scale=(iw*sar)*max(720/(iw*sar)\,480/ih):ih*max(720/(iw*sar)\,480/ih), crop=360:240" -c:v mpeg4 -vtag XVID -q:v 4 -c:a libmp3lame -q:a 4 scale.mkv





#flip video
#avconv -i output2.mkv -vf "hflip"  output3.mkv
	
#upload video	
youtube-upload --title="$video_title" --description="Copyright disclaimer! I do NOT own this $video_title video/song or the image featured in the video. All rights belong to it's rightful owner/owner's.No copyright infringement intended," --category=Music --tags="$video_title" --recording-date="2011-03-10T15:32:17.0Z" --default-language="en" --default-audio-language="en" --privacy="private" --playlist "mopi" "addmetadata.mp4"


#youtube-upload --title="$video_title" "out.mkv"


echo "pause 10 detik"

sleep 10

echo "proses upload selesai"
