#!/bin/bash
# run: source curl -s https://github.com/arsanto/auto/raw/master/enter.sh

rm -rf *.jpg
rm -rf *.mp3
rm -rf *.mp4
rm -rf *.mkv
rm -rf *.wav
rm -rf *.webm
rm -rf *.mov
rm -rf filename.*
address=$1
regex='v=(.*)'
if [[ $address =~ $regex ]]; then
video_id=${BASH_REMATCH[1]}
video_id=$(echo $video_id | cut -d'&' -f1)
video_title="$(youtube-dl --get-title $address)"
youtube-dl $address --output "filename.%(ext)s"
 else
    echo "Sorry but the system encountered a problem."
 fi

#ffmpeg -i filename.* -map_metadata -1 -vcodec copy -acodec copy nometadata.mkv

ffmpeg -i filename.* -map 0 -map_metadata 0:s:0 -c copy nometadata.mkv




ffmpeg -i nometadata.mkv \
	-map_metadata -1 \
	-metadata title="Btt Project" \
	-metadata author="Btt Project" \
	-metadata composer="Btt Project" \
	-metadata copyright="Copyright © 2016 Btt Project" \
	-c:v copy -c:a libmp3lame -q:a 9 -y out.mkv

 
#ffmpeg -i out.mkv -s 1024x600 -vf crop=480:480,setdar=1:1,setsar=1:1 -strict -2 output.mkv


ffmpeg -i out.mkv -vf "scale=(iw*sar)*max(720/(iw*sar)\,480/ih):ih*max(720/(iw*sar)\,480/ih), crop=360:240" -c:v mpeg4 -vtag XVID -q:v 4 -c:a libmp3lame -q:a 4 output1.mkv

ffmpeg -i output1.mkv -filter_complex "setpts=PTS/0.75;atempo=0.75" output2.mkv

youtube-upload --title="$video_title" --description="$video_title" --category=Music --tags="$video_title" --recording-date="2011-03-10T15:32:17.0Z" --default-language="en" --default-audio-language="en" --privacy="unlisted" output2.mkv


#youtube-upload --title="$video_title" output1.mkv


echo "proses upload selesai silahkan ganti judul"

